### ISSUE TITLE
这个项目有Maven坐标么

### ISSUE THREAD

**Issue by SylarChen** [daniellansun/groovy-parser#122]
想解析一些Groovy的Source Code，提取类中的方法名等数据。

@daniellansun 想请教下，能否使用这个项目去快速实现以上的需求。

例如像[JavaParser](https://javaparser.org/)去解析Java源文件一样。

**Comment by daniellansun** [comment]
> 这个项目有Maven坐标么

没有。不过该parser已经捐献给https://github.com/apache/groovy ，如果需要使用该parser，可以考虑引入`org.apache.groovy:groovy:4.0.1`

> 想解析一些Groovy的Source Code，提取类中的方法名等数据。

可以做到

**Comment by SylarChen** [comment]
> > 这个项目有Maven坐标么
> 
> 没有。不过该parser已经捐献给https://github.com/apache/groovy ，如果需要使用该parser，可以考虑引入`org.apache.groovy:groovy:4.0.1`
> 
> > 想解析一些Groovy的Source Code，提取类中的方法名等数据。
> 
> 可以做到

有如何使用的简单例子么

**Comment by daniellansun** [comment]
> > > 这个项目有Maven坐标么
> > 
> > 
> > 没有。不过该parser已经捐献给https://github.com/apache/groovy ，如果需要使用该parser，可以考虑引入`org.apache.groovy:groovy:4.0.1`
> > > 想解析一些Groovy的Source Code，提取类中的方法名等数据。
> > 
> > 
> > 可以做到
> 
> 有如何使用的简单例子么

可以参考博文中的最后一个例子：
https://blog.sunlan.me/2017/04/15/Groovy-3之新特性预览/

```groovy
def ast = new CompilationUnit().tap {
    addSource 'hello.groovy', code
    compile Phases.SEMANTIC_ANALYSIS 
}.ast
```

**Comment by SylarChen** [comment]
Thanks，弄通了
